os: linux

language: android

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

android:
  components:
  - tools-26.1.1
  - platform-tools-29.0.5
  - build-tools-29.0.2
  - android-29 # match your targetVersion android-29 old 28
  - extras-49
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

jdk: oraclejdk8

sudo: false

before_script:
  # Setup gradle.
  - wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
  - unzip -qq gradle-4.10.3-bin.zip
  - export GRADLE_HOME=`pwd`/gradle-4.10.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - mkdir -p /home/travis/.android
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  #- export SDKMANAGER_OPTS="--add-modules java.se.ee"
  #- yes | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses
  #- yes | flutter doctor --android-licenses
  - $ANDROID_HOME/tools/bin/sdkmanager --list

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid

cache:
  directories:
  - "$HOME/.pub-cache"


script: #install:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH="$PATH:`pwd`/flutter/bin"
- pwd
- ls -alh
- echo $PATH
- cd android
#- gradle build connectedCheck
- flutter doctor -v
