name: museum_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  gradient_text: ^1.0.2
  flutter_circular_chart: ^0.1.0
  charts_flutter: ^0.9.0
  flutter_rating_bar: ^3.0.1+1
  photo_view: ^0.9.2
  carousel_slider: ^2.1.0 #1.4.0
  graphql_flutter: ^3.0.0
  expandable: ^4.1.3
  intl: ^0.16.1
  expandable_bottom_bar: ^1.0.2 #0.1.1
  keyboard_visibility: ^0.5.6
  moor: ^3.3.1 #2.4.2
  sqlite3_flutter_libs: ^0.2.0
  # moor_ffi: ^0.5.0 #0.3.0 deprecated!
  path_provider: ^1.6.14
  path: ^1.7.0 #1.6.4
  provider: ^4.1.0 #4.0.2
  reorderables: ^0.3.2
  rxdart: ^0.23.1 #0.24.0
  md2_tab_indicator: ^1.0.2
  font_awesome_flutter: ^8.8.1 #8.7.0
  popup_menu: ^1.0.5
  open_file: ^3.0.1
  url_launcher: ^5.7.2 #5.3.0
  carousel_pro: ^1.0.0
  flutter_keyboard_visibility: ^3.0.0 #0.7.0
  flutter_linkify: ^3.1.3
  mutex: ^1.0.3
  overlay_container: ^0.0.4+1

dev_dependencies:
  #flutter_test:
   # sdk: flutter
  #test: ^1.9.0
  moor_generator: ^3.3.1 #2.4.0
  build_runner: ^1.10.1 #1.7.3
  flutter_launcher_icons: ^0.7.5 #0.7.3
  test: ^1.9.0 #1.5.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/AppIcon_G_vernetzt_NEW.png"
  adaptive_icon_background: "#FFFFFF"
  image_path_android: "assets/images/AppIcon_G_vernetzt_NEW_round.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/pdfs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
    - family: Chiller
      fonts:
        - asset: fonts/Chiller-Regular.ttf
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
